#!/usr/bin/env bash
pushd `dirname $(readlink $0)` > /dev/null
SCRIPTPATH=$(pwd -P)
popd > /dev/null

source $(readlink -e $(dirname $(which conda))/../etc/profile.d/conda.sh)

conda activate dicomtools
${SCRIPTPATH}/niftidiff.py "$@"
