#!/usr/bin/env bash
SCRIPTPATH=$(dirname $(readlink $(which dicomattribute)))
source virtualenvwrapper.sh
PYVER=3.6

lsvirtualenv -b |grep fsleyes >/dev/null
create_env=$?
if [ $create_env -eq 1 ]; then
  mkvirtualenv -p python$PYVER fsleyes
  workon fsleyes
  pip install fsleyes virtualenvwrapper
fi

workon fsleyes

WXPYTHON_APP=$(which fsleyes)

if [ -z "$VIRTUAL_ENV" ] ; then
    echo "You must activate your virtualenv: set '$VIRTUAL_ENV'"
    exit 1
fi

PYSUBVER="$(python --version 2>&1 | cut -d ' ' -f2)"  # e.g., 2.7.10

PYTHON_BINARY="bin/python$PYVER"
if [[ $OSX ]]; then
  SYSTEM_FRAMEWORK_PYTHON_ROOT="/Library/Frameworks/Python.framework/Versions/$PYVER"
  FRAMEWORK_PYTHON="$SYSTEM_FRAMEWORK_PYTHON_ROOT/$PYTHON_BINARY"
else
  FRAMEWORK_PYTHON=$(which python)
fi

# Use the Framework Python to run the app
export PYTHONHOME=$VIRTUAL_ENV
FSLDIR='/' exec "$FRAMEWORK_PYTHON" "$WXPYTHON_APP" $*
